export public FailedReceiptScan{
public recordId: string;
public userId: string;
public failureMessage: string;
public receiptType: string;
public partNumber: string;
public location: string;
public siteCode: string;
public refNumber: string;
public note: string;
public mfgPart: string;
public PO: string;
public f1: string;
public f2: string;
public f3: string;
public f4: string;
public f5: string;
public f6: string;
public f7: string;
public f8: string;
public f9: string;
public f10: string;
public packingSlipNum: string;
public companyId: number;
public orderQuantity: number;
public orderNumber: number;
public rfoNum: number;
public dateCreated: Date;
}